### ISSUE TITLE
Not working in ubuntu 20.04 

### ISSUE THREAD

**Issue by Electrik-rich546456** [MicahCarrick/gedit-restore-tabs#19]
I have gedit 3.36.2 and made the modifications on line 61 of the main py file but it still does not work.
I can see the following error if i run it from terminal.
```
gedit
Traceback (most recent call last):
  File "/home/user/.local/share/gedit/plugins/restoretabs.py", line 48, in on_window_delete_event
    gfile = document.get_location()
AttributeError: 'Document' object has no attribute 'get_location'

```
